feat: update security workflows

diff --git a/.github/workflows/security-scan.yaml b/.github/workflows/security-scan.yaml
--- a/.github/workflows/security-scan.yaml
+++ b/.github/workflows/security-scan.yaml
@@ -1,17 +1,55 @@
 name: security scan
 on:
-#   push:
-#     branches:
-#       - main
-#   pull_request:
+  push:
+    branches:
+      - 'feature/**'
+  pull_request:
+    branches:
+      - develop
   workflow_dispatch:
 permissions:
   security-events: write
   contents: read
+  actions: read
 jobs:
+  code-scan:
+    runs-on: 
+      labels: cmif-raas   
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: setup python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11' 
+
+      - name: setup python dependencies
+        run: |
+          pip install bandit
+
+      - name: scan python code
+        continue-on-error: true
+        run: |
+          bandit -f json -o code-report.json -r ./python_codes/ --severity-level medium --confidence-level medium
+          echo "exitcode=$?" >> $GITHUB_ENV
+          ls -la 
+
+      - name: Upload code report
+        uses: actions/upload-artifact@v4
+        with:
+          name: code-report
+          path: ./code-report.json
+
+      - name: Fail if Bandit found issues
+        if: env.exitcode != '0'        # chỉ chạy khi Bandit exit code ≠ 0
+        run: |
+          echo "🚨 Bandit detected vulnerabilities. Failing job."
+          exit 1
   repos-scan:
     name: repos-scan
     runs-on: ubuntu-24.04
+    needs: code-scan
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -29,11 +67,11 @@ jobs:
         run: |
           ls -la
 
-      # - name: Upload code report
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: repo-report
-      #     path: ./repo-report.sarif
+      - name: Upload code report
+        uses: actions/upload-artifact@v4
+        with:
+          name: repo-report
+          path: ./repo-report.sarif
     
       - name: Upload Trivy scan results to GitHub Security tab
         uses: github/codeql-action/upload-sarif@v3
@@ -43,7 +81,7 @@ jobs:
   image-scan:
     name: image-scan
     runs-on: ubuntu-24.04
-    needs: repos-scan
+    needs: [code-scan, repos-scan]
     # container:
     #   image: dzagob/debian:custom-tools-v7  # Container agent của bạn
     #   options: --privileged  # Bắt buộc để sử dụng DinD
@@ -74,11 +112,11 @@ jobs:
         run: |
             ls -la
 
-      # - name: upload artifacts
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: trivy-report
-      #     path: ./image-report.json
+      - name: upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: trivy-report
+          path: ./image-report.json
   
       - name: Generate and display vulnerability report
         run: |
@@ -93,71 +131,71 @@ jobs:
             echo "##[group]Vulnerability Report"
           fi
 
-  # notify_failure:
-  #   runs-on: 
-  #     labels: cmif-raas  
-  #   needs: [repos-scan, image-scan]
-  #   if: ${{ failure() }}
-  #   outputs:
-  #     issue_number: ${{ steps.set_output.outputs.issue_number }}
-  #   steps:
-  #     - name: Create issue
-  #       id: create-issue
-  #       uses: actions/github-script@v7
-  #       with:
-  #         script: |
-  #           try {
-  #             const prLink = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/pull/${context.issue.number}`;
-  #             const response = await github.rest.issues.create({
-  #               owner: context.repo.owner,
-  #               repo: context.repo.repo,
-  #               title: `[Scan Failed] Security scan failed in PR #${context.issue.number}`,
-  #               body: `Security scan failed in workflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}\n\nRelated PR: ${prLink}`
-  #             });
+  notify_failure:
+    runs-on: 
+      labels: cmif-raas  
+    needs: [code-scan, repos-scan, image-scan]
+    if: ${{ failure() }}
+    outputs:
+      issue_number: ${{ steps.set_output.outputs.issue_number }}
+    steps:
+      - name: Create issue
+        id: create-issue
+        uses: actions/github-script@v7
+        with:
+          script: |
+            try {
+              const prLink = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/pull/${context.issue.number}`;
+              const response = await github.rest.issues.create({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                title: `[Scan Failed] Security scan failed in PR #${context.issue.number}`,
+                body: `Security scan failed in workflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}\n\nRelated PR: ${prLink}`
+              });
               
-  #             // Lưu issue number vào biến môi trường
-  #             core.exportVariable('ISSUE_NUMBER', response.data.number);
-  #             return response.data.number;
-  #           } catch (error) {
-  #             core.error(`Failed to create issue: ${error}`);
-  #             core.setOutput('number', '0'); // Trả về '0' khi có lỗi
-  #             return 0;
-  #           }
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+              // Lưu issue number vào biến môi trường
+              core.exportVariable('ISSUE_NUMBER', response.data.number);
+              return response.data.number;
+            } catch (error) {
+              core.error(`Failed to create issue: ${error}`);
+              core.setOutput('number', '0'); // Trả về '0' khi có lỗi
+              return 0;
+            }
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
 
 
-  # report-to-pr:
-  #   name: Report results to PR
-  #   runs-on: 
-  #     labels: cmif-raas  
-  #   needs: [repos-scan, image-scan, notify_failure]  # Đợi cả 2 job hoàn thành
-  #   if: ${{ github.event_name == 'pull_request' && failure() }} # Chỉ chạy khi là PR
+  report-to-pr:
+    name: Report results to PR
+    runs-on: 
+      labels: cmif-raas  
+    needs: [code-scan, repos-scan, image-scan, notify_failure]  # Đợi cả 2 job hoàn thành
+    if: ${{ github.event_name == 'pull_request' && failure() }} # Chỉ chạy khi là PR
     
-  #   steps:
-  #     - name: Comment on PR with issue link
-  #       uses: actions/github-script@v7
-  #       with:
-  #         script: |
-  #           // Lấy issue number từ output
-  #           const issueNumber = "${{ needs.notify_failure.outputs.issue_number }}";
-  #           console.log(`Received issue number: ${issueNumber}`);
+    steps:
+      - name: Comment on PR with issue link
+        uses: actions/github-script@v7
+        with:
+          script: |
+            // Lấy issue number từ output
+            const issueNumber = "${{ needs.notify_failure.outputs.issue_number }}";
+            console.log(`Received issue number: ${issueNumber}`);
                       
-  #           // Kiểm tra nếu issueNumber hợp lệ
-  #           let issueLink = '';
-  #           if (issueNumber && issueNumber !== '0' && issueNumber !== '') {
-  #             issueLink = `\n\n⚠️ An issue has been created for this failure: [#${issueNumber}](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/issues/${issueNumber})`;
-  #           }
-  #           // Tạo nội dung comment
-  #           const commentBody = `❌ Security scans failed! [View details](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})${issueLink}`;
-  #           console.log(`Comment body: ${commentBody}`);
+            // Kiểm tra nếu issueNumber hợp lệ
+            let issueLink = '';
+            if (issueNumber && issueNumber !== '0' && issueNumber !== '') {
+              issueLink = `\n\n⚠️ An issue has been created for this failure: [#${issueNumber}](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/issues/${issueNumber})`;
+            }
+            // Tạo nội dung comment
+            const commentBody = `❌ Security scans failed! [View details](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})${issueLink}`;
+            console.log(`Comment body: ${commentBody}`);
 
-  #           // Tạo comment trong PR
-  #           await github.rest.issues.createComment({
-  #             owner: context.repo.owner,
-  #             repo: context.repo.repo,
-  #             issue_number: context.issue.number,
-  #             body: commentBody
-  #           });
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+            // Tạo comment trong PR
+            await github.rest.issues.createComment({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number,
+              body: commentBody
+            });
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
