feat: add job code scan to workflows

diff --git a/.github/workflows/security-scan.yaml b/.github/workflows/security-scan.yaml
--- a/.github/workflows/security-scan.yaml
+++ b/.github/workflows/security-scan.yaml
@@ -10,9 +10,44 @@ permissions:
   contents: read
   actions: read
 jobs:
+  code-scan:
+    runs-on: 
+      labels: cmif-raas   
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: setup python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11' 
+
+      - name: setup python dependencies
+        run: |
+          pip install bandit
+
+      - name: scan python code
+        continue-on-error: true
+        run: |
+          bandit -f json -o code-report.json -r ./python_codes/ --severity-level medium --confidence-level medium
+          echo "exitcode=$?" >> $GITHUB_ENV
+          ls -la 
+
+      - name: Upload code report
+        uses: actions/upload-artifact@v3
+        with:
+          name: code-report
+          path: ./code-report.json
+
+      - name: Fail if Bandit found issues
+        if: env.exitcode != '0'        # chỉ chạy khi Bandit exit code ≠ 0
+        run: |
+          echo "🚨 Bandit detected vulnerabilities. Failing job."
+          exit 1
   repos-scan:
     name: repos-scan
     runs-on: ubuntu-24.04
+    needs: code-scan
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -44,7 +79,7 @@ jobs:
   image-scan:
     name: image-scan
     runs-on: ubuntu-24.04
-    needs: repos-scan
+    needs: [code-scan, repos-scan]
     # container:
     #   image: dzagob/debian:custom-tools-v7  # Container agent của bạn
     #   options: --privileged  # Bắt buộc để sử dụng DinD
@@ -97,7 +132,7 @@ jobs:
   notify_failure:
     runs-on: 
       labels: cmif-raas  
-    needs: [repos-scan, image-scan]
+    needs: [code-scan, repos-scan, image-scan]
     if: ${{ failure() }}
     outputs:
       issue_number: ${{ steps.set_output.outputs.issue_number }}
@@ -132,7 +167,7 @@ jobs:
     name: Report results to PR
     runs-on: 
       labels: cmif-raas  
-    needs: [repos-scan, image-scan, notify_failure]  # Đợi cả 2 job hoàn thành
+    needs: [code-scan, repos-scan, image-scan, notify_failure]  # Đợi cả 2 job hoàn thành
     if: ${{ github.event_name == 'pull_request' && failure() }} # Chỉ chạy khi là PR
     
     steps:
