update

diff --git a/.github/workflows/security-scan.yaml b/.github/workflows/security-scan.yaml
--- a/.github/workflows/security-scan.yaml
+++ b/.github/workflows/security-scan.yaml
@@ -30,10 +30,10 @@ jobs:
         with:
           image-ref: 'docker.io/dzagob/python_app:fake-log-v3'
           format: 'json'
-          ignore-unfixed: false
+          ignore-unfixed: true
           vuln-type: 'os,library'
           output: 'image-report.json'
-          #severity: 'CRITICAL,HIGH,MEDIUM,LOW'
+          severity: 'CRITICAL,HIGH'
 
       - name: check files
         run: |
@@ -44,7 +44,19 @@ jobs:
         with:
           name: trivy-report
           path: ./image-report.json
+  
+      - name: Generate and display vulnerability report
+        run: |
+          sudo apt-get install -y jq
+          critical_count=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity == "CRITICAL")] | length' image-report.json)
+          high_count=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity == "HIGH")] | length' image-report.json)
 
+          if [ "$critical_count" -gt 0 ] || [ "$high_count" -gt 0 ]; then
+            echo "##[error]Found $critical_count CRITICAL and $high_count HIGH vulnerabilities"
+            exit 1
+          else
+            echo "##[group]Vulnerability Report"
+          fi
     #   - name: Upload Trivy scan results to GitHub Security tab
     #     uses: github/codeql-action/upload-sarif@v3
     #     with:
